[".config/alacritty/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/alacritty.git"
refreshPeriod = "168h"

[".githelpers"]
type = "file"
url = "https://raw.githubusercontent.com/stevearc/dotfiles/master/.githelpers"
refreshPeriod = "168h"

[".config/yazi/theme.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/yazi/main/themes/mocha.toml"
refreshPeriod = "168h"

[".config/yazi/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"

[".config/delta/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/delta.git"
refreshPeriod = "168h"

[".config/kitty/themes/mocha.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/mocha.conf"
refreshPeriod = "168h"

[".config/glow/themes/catppuccin-mocha.json"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/glamour/main/themes/catppuccin-mocha.json"
refreshPeriod = "168h"
