# OH-MY-ZSH

[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"

[".oh-my-zsh/custom/plugins/fzf-tab"]
type = "git-repo"
url = "https://github.com/Aloxaf/fzf-tab.git"

[".oh-my-zsh/custom/plugins/wakatime"]
type = "git-repo"
url = "https://github.com/sobolevn/wakatime-zsh-plugin.git"

[".oh-my-zsh/custom/plugins/zsh-256color"]
type = "git-repo"
url = "https://github.com/chrissicool/zsh-256color.git"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"

[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
type = "git-repo"
url = "https://github.com/marlonrichert/zsh-autocomplete.git"

##########################################

# GITS

[".gits/useful-script"]
type = "git-repo"
url = "https://github.com/HoangTran0410/useful-script.git"

# DCMA Taken down
# [".gits/bypass-paywalls-chrome"]
# type = "git-repo"
# url = "https://github.com/iamadamdev/bypass-paywalls-chrome.git"

##########################################

# CONFIG

[".config/nvim"]
type = "git-repo"
url = "git@github.com:KevinNitroG/Alexis12119-nvim.git"

[".config/alacritty/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/alacritty.git"

[".config/yazi/theme.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/yazi/main/themes/mocha.toml"

[".config/yazi/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"

[".config/delta/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/delta.git"

[".config/kitty/themes/mocha.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/mocha.conf"

[".config/glow/themes/catppuccin-mocha.json"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/glamour/main/themes/catppuccin-mocha.json"

[".config/zathura/catppuccin-mocha"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zathura/main/src/catppuccin-mocha"

[".config/sddm/themes/"]
type = "archive"
url = "https://github.com/catppuccin/sddm/releases/latest/download/catppuccin-mocha.zip"
include = ["**/*"]

[".config/atac/key_bindings.toml"]
type = "file"
url = "https://raw.githubusercontent.com/Julien-cpsn/ATAC/main/key_bindings_templates/vim_key_bindings.toml"

##########################################

# UTILS

[".githelpers"]
type = "file"
url = "https://raw.githubusercontent.com/stevearc/dotfiles/master/.githelpers"
