prSections:
  - title: All
    filters: author:@me
  - title: All open
    filters: is:open author:@me
  - title: Commented
    filters: commenter:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
issuesSections:
  - title: All
    filters: author:@me
  - title: All open
    filters: is:open author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: false
      base:
        width: 15
        hidden: false
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: false
  refetchIntervalMinutes: 30
keybindings:
  issues:
    - key: P
      command: gh issue pin {{.IssueNumber}} --repo {{.RepoName}}
  prs:
    - key: O
      builtin: checkout
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen master...{{.HeadRefName}}"
        '
    - key: v
      command: >
        cd {{.RepoPath}} &&
        code . &&
        gh pr checkout {{.PrNumber}}
repoPaths:
  "*": ~/gits/gh-dash-pr/*
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#f9e2af"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f38ba8"
      success: "#a6e3a1"
    background:
      selected: "#313244"
    border:
      primary: "#f9e2af"
      secondary: "#45475a"
      faint: "#313244"
pager:
  diff: "delta" # delta | less
